// Lista curada de insumos farmacêuticos ativos (IFAs) mais usados em
// farmácias de manipulação no Brasil. Não existe uma API pública oficial
// para "medicamentos manipulados" (eles são fórmulas sob prescrição, não
// produtos registrados na ANVISA), então esta base serve como catálogo de
// referência para preenchimento rápido de fórmulas magistrais.
export const MANIPULADOS_SEED = [
  {
    nome: "Minoxidil",
    principio_ativo: "minoxidil",
    categoria: "Capilar",
    forma_farmaceutica: "Solução tópica",
  },
  {
    nome: "Finasterida",
    principio_ativo: "finasterida",
    categoria: "Capilar",
    forma_farmaceutica: "Cápsula / tópico",
  },
  {
    nome: "Cafeína",
    principio_ativo: "cafeína",
    categoria: "Capilar / Emagrecimento",
    forma_farmaceutica: "Solução / creme",
  },
  {
    nome: "Melatonina",
    principio_ativo: "melatonina",
    categoria: "Sono",
    forma_farmaceutica: "Cápsula / sublingual",
  },
  {
    nome: "Vitamina D3 (Colecalciferol)",
    principio_ativo: "colecalciferol",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula / gotas",
  },
  {
    nome: "5-MTHF (Metilfolato)",
    principio_ativo: "metilfolato",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Coenzima Q10",
    principio_ativo: "ubiquinona",
    categoria: "Antioxidante",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Resveratrol",
    principio_ativo: "resveratrol",
    categoria: "Antioxidante",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Colágeno Verisol",
    principio_ativo: "peptídeos de colágeno",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Sachê / cápsula",
  },
  {
    nome: "Ácido Hialurônico",
    principio_ativo: "ácido hialurônico",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Cápsula / creme",
  },
  {
    nome: "Niacinamida",
    principio_ativo: "niacinamida",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Creme / sérum",
  },
  {
    nome: "Tretinoína",
    principio_ativo: "tretinoína",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Creme",
  },
  {
    nome: "Ácido Kójico",
    principio_ativo: "ácido kójico",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Creme",
  },
  {
    nome: "Alfa Arbutin",
    principio_ativo: "alfa-arbutina",
    categoria: "Dermocosmético",
    forma_farmaceutica: "Creme / sérum",
  },
  {
    nome: "Vitamina C (Ácido Ascórbico)",
    principio_ativo: "ácido ascórbico",
    categoria: "Dermocosmético / Suplemento",
    forma_farmaceutica: "Sérum / cápsula",
  },
  {
    nome: "Biotina",
    principio_ativo: "biotina",
    categoria: "Capilar / Suplemento",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Zinco Quelato",
    principio_ativo: "zinco",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Magnésio Dimalato",
    principio_ativo: "magnésio",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Ômega 3",
    principio_ativo: "EPA/DHA",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Curcumina (Cúrcuma)",
    principio_ativo: "curcumina",
    categoria: "Antioxidante / Anti-inflamatório",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Berberina",
    principio_ativo: "berberina",
    categoria: "Metabólico",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "L-Carnitina",
    principio_ativo: "L-carnitina",
    categoria: "Emagrecimento",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Picolinato de Cromo",
    principio_ativo: "cromo",
    categoria: "Emagrecimento",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Orlistat manipulado",
    principio_ativo: "orlistat",
    categoria: "Emagrecimento",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Sibutramina",
    principio_ativo: "sibutramina",
    categoria: "Emagrecimento",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Progesterona Micronizada",
    principio_ativo: "progesterona",
    categoria: "Hormonal",
    forma_farmaceutica: "Cápsula / creme",
  },
  {
    nome: "Estradiol",
    principio_ativo: "estradiol",
    categoria: "Hormonal",
    forma_farmaceutica: "Creme / gel transdérmico",
  },
  {
    nome: "Testosterona",
    principio_ativo: "testosterona",
    categoria: "Hormonal",
    forma_farmaceutica: "Gel / cápsula",
  },
  {
    nome: "DHEA",
    principio_ativo: "deidroepiandrosterona",
    categoria: "Hormonal",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Latanoprosta",
    principio_ativo: "latanoprosta",
    categoria: "Capilar (cílios/sobrancelhas)",
    forma_farmaceutica: "Solução tópica",
  },
  {
    nome: "Ansiolin (fórmula ansiolítica natural)",
    principio_ativo: "passiflora + valeriana",
    categoria: "Sono/Ansiedade",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "GABA",
    principio_ativo: "ácido gama-aminobutírico",
    categoria: "Sono/Ansiedade",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "L-Teanina",
    principio_ativo: "L-teanina",
    categoria: "Sono/Ansiedade",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "5-HTP",
    principio_ativo: "5-hidroxitriptofano",
    categoria: "Sono/Ansiedade",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Glutationa",
    principio_ativo: "glutationa reduzida",
    categoria: "Antioxidante",
    forma_farmaceutica: "Cápsula / sublingual",
  },
  {
    nome: "NAC (N-acetilcisteína)",
    principio_ativo: "acetilcisteína",
    categoria: "Antioxidante",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Probióticos manipulados",
    principio_ativo: "lactobacillus / bifidobacterium",
    categoria: "Digestivo",
    forma_farmaceutica: "Cápsula / sachê",
  },
  {
    nome: "Simeticona manipulada",
    principio_ativo: "simeticona",
    categoria: "Digestivo",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Ácido Fólico",
    principio_ativo: "ácido fólico",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Vitamina B12 (Metilcobalamina)",
    principio_ativo: "metilcobalamina",
    categoria: "Suplemento/Vitamina",
    forma_farmaceutica: "Cápsula / sublingual",
  },
];
