// Lista curada de medicamentos e produtos industrializados (de balcão) mais
// comuns numa farmácia popular brasileira. Diferente dos manipulados, estes
// SÃO produtos registrados na ANVISA — o ideal é importar os dados oficiais
// via medicamentos.api.br (nome exato, registro, fabricante, preço CMED).
// Esta lista serve como catálogo de referência offline, disponível mesmo
// sem configurar a chave da API, pra farmácia não começar com a busca de
// "Não manipulados" totalmente vazia. As categorias usadas aqui batem com
// as opções de categoria do cadastro de Estoque Não Manipulados.
export const INDUSTRIALIZADOS_SEED = [
  {
    nome: "Paracetamol 750mg",
    principio_ativo: "paracetamol",
    categoria: "Analgésico",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Dipirona Sódica 500mg",
    principio_ativo: "dipirona sódica",
    categoria: "Analgésico",
    fabricante: "Medley",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Dipirona Sódica Gotas",
    principio_ativo: "dipirona sódica",
    categoria: "Analgésico",
    fabricante: "EMS",
    forma_farmaceutica: "Solução oral",
  },
  {
    nome: "Dorflex",
    principio_ativo: "dipirona + orfenadrina + cafeína",
    categoria: "Analgésico",
    fabricante: "Sanofi",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Paracetamol Gotas Infantil",
    principio_ativo: "paracetamol",
    categoria: "Antitérmico",
    fabricante: "Neo Química",
    forma_farmaceutica: "Solução oral",
  },
  {
    nome: "Ibuprofeno 400mg",
    principio_ativo: "ibuprofeno",
    categoria: "Anti-inflamatório",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Diclofenaco Sódico Gel",
    principio_ativo: "diclofenaco sódico",
    categoria: "Anti-inflamatório",
    fabricante: "Medley",
    forma_farmaceutica: "Gel tópico",
  },
  {
    nome: "Nimesulida 100mg",
    principio_ativo: "nimesulida",
    categoria: "Anti-inflamatório",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Loratadina 10mg",
    principio_ativo: "loratadina",
    categoria: "Antialérgico",
    fabricante: "Medley",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Cetirizina 10mg",
    principio_ativo: "cetirizina",
    categoria: "Antialérgico",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Desloratadina 5mg",
    principio_ativo: "desloratadina",
    categoria: "Antialérgico",
    fabricante: "Neo Química",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Vitamina C 1g Efervescente",
    principio_ativo: "ácido ascórbico",
    categoria: "Vitaminas/Suplementos",
    fabricante: "Redoxon",
    forma_farmaceutica: "Comprimido efervescente",
  },
  {
    nome: "Complexo B",
    principio_ativo: "vitaminas do complexo B",
    categoria: "Vitaminas/Suplementos",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Vitamina D3 2000UI",
    principio_ativo: "colecalciferol",
    categoria: "Vitaminas/Suplementos",
    fabricante: "Addera",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Sulfato Ferroso 40mg",
    principio_ativo: "sulfato ferroso",
    categoria: "Vitaminas/Suplementos",
    fabricante: "EMS",
    forma_farmaceutica: "Comprimido",
  },
  {
    nome: "Protetor Solar FPS 60",
    principio_ativo: "-",
    categoria: "Higiene/Dermocosmético",
    fabricante: "La Roche-Posay",
    forma_farmaceutica: "Loção",
  },
  {
    nome: "Álcool em Gel 70%",
    principio_ativo: "-",
    categoria: "Higiene/Dermocosmético",
    fabricante: "Rioquímica",
    forma_farmaceutica: "Gel",
  },
  {
    nome: "Sabonete Antisséptico",
    principio_ativo: "triclosan",
    categoria: "Higiene/Dermocosmético",
    fabricante: "Protex",
    forma_farmaceutica: "Barra",
  },
  {
    nome: "Hidratante Corporal",
    principio_ativo: "-",
    categoria: "Higiene/Dermocosmético",
    fabricante: "Nivea",
    forma_farmaceutica: "Loção",
  },
  {
    nome: "Repelente de Insetos",
    principio_ativo: "icaridina",
    categoria: "Higiene/Dermocosmético",
    fabricante: "Johnson & Johnson",
    forma_farmaceutica: "Aerossol/Loção",
  },
  {
    nome: "Soro Fisiológico 0,9%",
    principio_ativo: "cloreto de sódio",
    categoria: "Outros",
    fabricante: "Eurofarma",
    forma_farmaceutica: "Solução",
  },
  {
    nome: "Escopolamina (Buscopan)",
    principio_ativo: "escopolamina",
    categoria: "Outros",
    fabricante: "Sanofi",
    forma_farmaceutica: "Comprimido/Gotas",
  },
  {
    nome: "Omeprazol 20mg",
    principio_ativo: "omeprazol",
    categoria: "Outros",
    fabricante: "EMS",
    forma_farmaceutica: "Cápsula",
  },
  {
    nome: "Antiácido (Hidróxido de Alumínio/Magnésio)",
    principio_ativo: "hidróxido de alumínio + magnésio",
    categoria: "Outros",
    fabricante: "Bayer",
    forma_farmaceutica: "Comprimido mastigável",
  },
  {
    nome: "Xarope Expectorante",
    principio_ativo: "guaifenesina",
    categoria: "Outros",
    fabricante: "Neo Química",
    forma_farmaceutica: "Xarope",
  },
  {
    nome: "Colírio Lubrificante",
    principio_ativo: "carboximetilcelulose",
    categoria: "Outros",
    fabricante: "Allergan",
    forma_farmaceutica: "Solução oftálmica",
  },
];
